- package.json
This PR removes the package engines to minimize incompatible engine errors.
At my work (and in personal projects) our environments all run different node/npm versions (both current and LTS) so dynamodb-admin doesn't install smoothly because of the engines set in the package.json. Because of this we have the bad practice of using the `--ignore-engines` flag.
> Removes package engines

- views/scan.ejs
Converted data to table format instead of a generic dump of the data.
This allows the data to be more easily parsable.
Signed-off-by: Nate Brunette <n@tebru.net>
> Updating scan view to display a table

- package.json
PR #12 introduced bower dependency, but it was added as a dev dependency, so when we installed this package with `npm i dynamodb-admin`, it was unable to run the bower command.
I could reproduce the error, and moving from dev to regular dependency fixed it.
Thanks @msaglietto for pointing this.
@aaronshaf This PR is kinda important because installation from `npm` is crashing for those who don't have `bower` command available
Closes #13
> Moved bower dependency from dev to regular dependency section

- index.js
- Starting server explicitly on host 127.0.0.1 instead of default 0.0.0.0.
- Logging server address to make it easier to open the gui after starting server.
> Don't listen on broadcast address and log server address on starting

- __tests__/extractKeysForItems.js
- index.js
- util.js
- views/scan.ejs
Getting keys from all the items, not only first, as first might
not have keys that later items have.
> Fix keys not shown when don't exist on first item (fixes #24)

- index.js
Otherwise they just show up as [Object object]
> Stringify fields containing maps

- README.md
- bin/dynamodb-admin.js
The PORT environment variable will still override port specified on
command line.
> Add -p/--port command line option to specify port to run on (#38)

- bin/dynamodb-admin.js
https://github.com/nodeca/argparse/blob/master/README.md says:
`Use defaultValue instead of default.`
> Fix invalid properties for default value of argument

- lib/backend.js
The `ListTables` API call returns [100 entries](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#listTables-property) by default, but some crazy people have lots of tables 🙃
> Evaluate all pages for ListTables call

- views/tables.ejs
Hello, I stumbled upon a bug where deleting a table refreshes the page and results in an unfinished request to the server. 
While fixing it I also added a small confirm() message to avoid unwillingly deleting a table.
> Added delete table confirmation + fix page refresh

- lib/backend.js
If multiple chunked scan queries would end up at exactly page size limit (25)
then even if there would be more items to query, we would not enable it.
Fixe by letting the number of items get over the limit which ensures that
the `done` callback slices items to limit and extracts last key.
> Fix disabled pagination in certain corner-case (#44)

- lib/backend.js
- views/get.ejs
- views/meta.ejs
- views/scan.ejs
This adds some basic support for scanning and querying indexes, helpful
when developing with indexes to see what data is being projected into
a index or to test queries.
It adds basic support for some query operators beyond the "is equal"
comparison, but this does not add rich operators like BETWEEN, begins
with, attribute exists, attribute does not exist, NULL, NOT, NULL, IN,
NOT IN, or the contains operators.
Renamed the "Scan" page to "Items", since Scan does not sound
appropriate given the new capabilities.
> Add support for scanning and querying indexes and some query operators

- lib/backend.js
…names.
Instead of expression attribute names being escaped as `#${key}`, they are now escaped as `#key${i}`, where `i` is unique for each attribute name.
This change converts requests to DynamoDB like this:
```javascript
ExpressionAttributeNames: {
'#my.expression.name.with.reserved.words': 'foo',
'#my.other.expression.name.with.reserved.words': 'bar'
}
```
to requests like this:
```javascript
ExpressionAttributeNames: {
'#key1': 'foo',
'#key2': 'bar'
}
```
preventing issues with invalid attribute names.
> fix: escape keys properly for expression attribute names

- README.md
- bin/dynamodb-admin.js
Addition of an host option alongside the existing port option to allow the server to bind to a specific network interface.
Either pass `--host/-H` to `dynamodb-admin.js` or set the environment variable `HOST`.
- Backwards compatible
- Useful when dockerized and using multiple networks (amongst other situations)
> Add Host option

- bin/dynamodb-admin.js
Default host should be undefined so that the app is listening on a broadcast address and we don't change the behavior that we had before.
This is also necessary for our docker container to work by default.
> fix: switch back default host to undefined

- views/scan.ejs
Unfortunately it's impossible to search for an empty value in the sort key since the UI ignores filters with empty values. Not sure if that's something worth addressing but it would probably require re-thinking how the filters are presented in the UI.
But to be fair it worked like that also before this change as the UI required to put something in the sort key value.
Fixes #143
> fix: make range (sort) key optional

- README.md
Adding this short note to help others with [a problem I faced](https://github.com/aaronshaf/dynamodb-admin/issues/219) where I could not access my `dynamodb-admin` data from a Java app until I made sure the keys matched. Thanks for your time
> docs: Add note about access keys

- views/scan.ejs
I've updated the styling of the table that lists all the items under a particular DynamoDB table page. 
- Updates the first row to be a `th` instead of `td` and its background is now light grey in color.
- Makes the table responsive by using an appropriate Bootstrap class.
- Makes the "Actions" column (first column) sticky so that users can easily click on the "View" link while scrolling horizontally through a large row item. 
- Every row has a style on hover that makes it easier to spot.
**Note:** The values in the above screenshot have been masked.
These styling changes make it easier to navigate rows with long string values. They improve the experience problems highlighted under https://github.com/aaronshaf/dynamodb-admin/issues/92.
> Enhances the styling of the items table 

- lib/backend.js
Added to createServer function a parameter to allow the inject of express instance to the library
> fix: allow passing custom express instance to createServer

- views/scan.ejs
Add heuristics for checking whether number is a timestamp and try to guess whether it represents seconds or milliseconds from epoch.
Resolves #244
> feat: guess whether timestamp is in seconds or milliseconds

- views/item.ejs
> fix: encode table name in the breadcrumb
